name: 🐛 Баг-репорт
description: Если что-то работает не так.
labels: ["status:triage", "type:bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: The text area is empty
    validations:
      required: true
- type: textarea
  id: correct-behaviour
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen
    placeholder: The text area is empty
  validations:
    required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce?
      description: Steps to reproduce the behavior
      placeholder: The text area is empty
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: The text area is empty
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contacts
      description: If we want to contact you how we can do it?
      placeholder: "An example, discord ID"
    validations:
      required: false
